version: 2
updates:
  - package-ecosystem: npm
    target-branch: develop
    directory: '.'
    schedule:
      interval: weekly
    allow:
      - dependency-type: development
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
